# Generated by Django 5.1.6 on 2025-03-21 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default='Test45', max_length=255),
            preserve_default=False,
        ),
    ]
