# Generated by Django 5.1.6 on 2025-03-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_avatar_face_location_avatar_hair_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('file_location', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('hair', 'Hair'), ('face', 'Face'), ('skin', 'Skin')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='face_location',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='file_location',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='hair_location',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='skin_location',
        ),
        migrations.AddField(
            model_name='avatar',
            name='face',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avface', to='mysite.avatarattribute'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='hair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avhair', to='mysite.avatarattribute'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='skin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avskin', to='mysite.avatarattribute'),
        ),
    ]
