# Generated by Django 5.1.6 on 2025-03-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_avatarattribute_remove_avatar_face_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='face',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='hair',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='skin',
        ),
        migrations.AddField(
            model_name='avatar',
            name='face',
            field=models.ManyToManyField(blank=True, null=True, related_name='avface', to='mysite.avatarattribute'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='hair',
            field=models.ManyToManyField(blank=True, null=True, related_name='avhair', to='mysite.avatarattribute'),
        ),
        migrations.AddField(
            model_name='avatar',
            name='skin',
            field=models.ManyToManyField(blank=True, null=True, related_name='avskin', to='mysite.avatarattribute'),
        ),
    ]
