# Generated by Django 5.1.6 on 2025-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_remove_avatar_face_remove_avatar_hair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='face',
            field=models.ManyToManyField(related_name='avface', to='mysite.avatarattribute'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hair',
            field=models.ManyToManyField(related_name='avhair', to='mysite.avatarattribute'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='skin',
            field=models.ManyToManyField(related_name='avskin', to='mysite.avatarattribute'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ManyToManyField(related_name='avatar', to='mysite.avatar'),
        ),
    ]
