# Generated by Django 5.1.6 on 2025-03-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_userprofile_avatar_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='hair',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='face',
        ),
        migrations.AddField(
            model_name='avatar',
            name='file_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AvatarAttribute',
        ),
    ]
